title: Thomas Devine's Portfolio
description: devinesworks.dev

theme: just-the-docs
color_scheme: "dark"

remote-theme: just-the-docs/just-the-docs

url: https://devinesworks.dev

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://devinesworks.dev

plugins:
- jekyll-include-cache

